import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../../theme';

const styles = StyleSheet.create({
  container: {
    padding: 16,
    paddingBottom: 40,
    backgroundColor: '#FAF8F5',
  },
  maxWidthWrapper: {
    width: '100%',
    maxWidth: 920,
    alignSelf: 'center',
  },
  timeFilterRow: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 4,
    marginBottom: 16,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: 'rgba(153, 8, 8, 0.08)',
  },
  timeChip: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 10,
    alignItems: 'center',
  },
  timeChipActive: {
    backgroundColor: COLORS.primary,
  },
  timeChipText: {
    fontFamily: FONTS.semiBold,
    fontSize: 13,
    color: COLORS.mutedText,
  },
  timeChipTextActive: {
    color: '#fff',
    fontFamily: FONTS.bold,
  },
  subOptionRow: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 3,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(148, 182, 239, 0.3)',
  },
  subOptionTab: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 9,
    alignItems: 'center',
  },
  subOptionTabActive: {
    backgroundColor: COLORS.primary,
  },
  subOptionText: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: COLORS.primary,
  },
  subOptionTextActive: {
    color: '#fff',
    fontFamily: FONTS.bold,
  },
  contentContainer: {
    gap: 16,
  },
  purposeCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 20,
    borderLeftWidth: 6,
    borderLeftColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(153, 8, 8, 0.06)',
  },
  badgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  purposeBadge: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.primary,
    letterSpacing: 1.2,
  },
  gradePill: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#A5D6A7',
  },
  gradePillText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
  },
  purposeTitle: {
    fontFamily: FONTS.bold,
    fontSize: 20,
    color: '#2B1212',
    marginBottom: 4,
  },
  purposeSub: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: COLORS.mutedText,
    lineHeight: 19,
    marginBottom: 14,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F8FF',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D0E1FD',
  },
  scoreBadge: {
    flexDirection: 'row',
    alignItems: 'baseline',
    backgroundColor: COLORS.primary,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 12,
    marginRight: 14,
  },
  scoreValue: {
    fontFamily: FONTS.bold,
    fontSize: 22,
    color: '#fff',
  },
  scoreMax: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
  },
  scoreTextContainer: {
    flex: 1,
  },
  scoreTitle: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: COLORS.primary,
  },
  scoreDesc: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.mutedText,
  },
  insightHighlightBox: {
    flexDirection: 'row',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    alignItems: 'center',
    borderWidth: 1,
  },
  insightIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  insightHighlightIcon: {
    fontSize: 20,
  },
  insightHighlightText: {
    flex: 1,
  },
  insightHighlightTitle: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    marginBottom: 2,
  },
  insightHighlightSub: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: '#4A3B32',
    lineHeight: 17,
  },
  sectionHeaderTitle: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.primary,
    letterSpacing: 1.5,
    marginTop: 8,
    marginBottom: 10,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metricCard: {
    width: Platform.OS === 'web' ? '31.8%' : '48%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderTopWidth: 4,
    borderWidth: 1,
    borderColor: 'rgba(153, 8, 8, 0.05)',
  },
  metricCardTop: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  metricIconBg: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricIcon: {
    fontSize: 18,
  },
  rdiBadge: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: '#F57C00',
    backgroundColor: '#FFF3E0',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
  },
  metricValue: {
    fontFamily: FONTS.bold,
    fontSize: 22,
    color: COLORS.primary,
  },
  metricUnit: {
    fontSize: 13,
    fontFamily: FONTS.regular,
    color: COLORS.mutedText,
  },
  metricLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: COLORS.mutedText,
    marginTop: 2,
    marginBottom: 10,
  },
  miniProgressBg: {
    width: '100%',
    height: 5,
    borderRadius: 3,
    backgroundColor: '#F0F0F0',
    overflow: 'hidden',
  },
  miniProgressFill: {
    height: '100%',
    borderRadius: 3,
  },
  energyRow: {
    flexDirection: 'row',
    gap: 10,
  },
  energyCard: {
    flex: 1,
    padding: 14,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
  },
  energyVal: {
    fontFamily: FONTS.bold,
    fontSize: 17,
    marginBottom: 2,
  },
  energyLabel: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.primary,
  },
  energySub: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: COLORS.mutedText,
    marginTop: 2,
  },
  itemTable: {
    width: '100%',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#EDE7F6',
  },
  itemTableHeader: {
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  itemHeadText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#fff',
  },
  itemTableRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  itemBodyText: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: COLORS.primary,
  },
  itemSubText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.mutedText,
  },
  itemColName: { flex: 2.2 },
  itemColCat: { flex: 1.8 },
  itemColCal: { flex: 1.2, textAlign: 'center' },
  itemColProt: { flex: 1.2, textAlign: 'center' },
  itemColTag: { flex: 1.6, alignItems: 'flex-end' },
  itemTypeBadge: {
    fontFamily: FONTS.bold,
    fontSize: 9,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  recommendationRow: {
    flexDirection: 'row',
    backgroundColor: '#FFF8F0',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#FFE0B2',
    alignItems: 'flex-start',
  },
  recIcon: {
    fontSize: 22,
    marginRight: 12,
    marginTop: 2,
  },
  recTextCol: {
    flex: 1,
  },
  recTitle: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: '#E65100',
    marginBottom: 3,
  },
  recDesc: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: '#4A3B32',
    lineHeight: 18,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 20,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(153, 8, 8, 0.05)',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badgePillText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#2E7D32',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
  },
  cardHeaderTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: COLORS.primary,
    marginBottom: 14,
  },
  cardTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: COLORS.primary,
  },
  cardSub: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.mutedText,
    marginBottom: 14,
    marginTop: 2,
  },
  progressContainer: {
    height: 18,
    borderRadius: 9,
    backgroundColor: '#E8E8E8',
    flexDirection: 'row',
    overflow: 'hidden',
    marginBottom: 14,
  },
  progressBar: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressPctInside: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: '#fff',
  },
  legendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  legendText: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: COLORS.mutedText,
  },
  macroBarContainer: {
    height: 16,
    borderRadius: 8,
    flexDirection: 'row',
    overflow: 'hidden',
    marginBottom: 14,
  },
  macroSegment: {
    height: '100%',
  },
  macroGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  macroItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  macroDotCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  macroText: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: COLORS.mutedText,
  },
  trendHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 10,
    alignItems: 'center',
    marginBottom: 6,
  },
  gainMuscleNavBtn: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 50,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    marginTop: 16,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  gainMuscleNavBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: '#fff',
    letterSpacing: 0.5,
  },
  trendBadgePill: {
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  trendBadgePillText: {
    fontFamily: FONTS.bold,
    fontSize: 9,
    color: '#1976D2',
    letterSpacing: 0.5,
  },
  viewModeToggleRow: {
    flexDirection: 'row',
    backgroundColor: '#F0F4FA',
    borderRadius: 8,
    padding: 2,
  },
  viewModeBtn: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  viewModeBtnActive: {
    backgroundColor: COLORS.primary,
  },
  viewModeText: {
    fontFamily: FONTS.semiBold,
    fontSize: 11,
    color: COLORS.primary,
  },
  viewModeTextActive: {
    color: '#fff',
    fontFamily: FONTS.bold,
  },

  growthSummaryBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#A5D6A7',
  },
  growthSummaryIcon: {
    fontSize: 22,
    marginRight: 12,
  },
  growthSummaryTitle: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: '#2E7D32',
    marginBottom: 2,
  },

  creativeCardsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  creativeReceiptCard: {
    width: Platform.OS === 'web' ? '18.8%' : '48%',
    backgroundColor: '#FAF8F5',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#EFEBE4',
  },
  creativeReceiptCardLatest: {
    backgroundColor: '#F1F8F3',
    borderColor: '#A5D6A7',
    borderWidth: 1.5,
  },
  rcTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  rcHeaderBadge: {
    backgroundColor: 'rgba(153, 8, 8, 0.08)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  rcIconText: {
    fontFamily: FONTS.bold,
    fontSize: 8,
    color: COLORS.primary,
  },
  rcGradePill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  rcGradeText: {
    fontFamily: FONTS.bold,
    fontSize: 9,
  },
  rcStoreName: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.primary,
    marginBottom: 2,
  },
  rcSubText: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: COLORS.mutedText,
    marginBottom: 8,
  },
  rcMeterBg: {
    width: '100%',
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E0E0E0',
    overflow: 'hidden',
  },
  rcMeterFill: {
    height: '100%',
    borderRadius: 3,
  },

  chartBarRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: 140,
    paddingTop: 12,
  },
  chartBarCol: {
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  chartBarVal: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.primary,
    marginBottom: 4,
  },
  chartBarBg: {
    width: 22,
    height: 85,
    backgroundColor: '#F0F4FA',
    borderRadius: 11,
    justify: 'flex-end',
    overflow: 'hidden',
  },
  chartBarFill: {
    width: '100%',
    borderRadius: 11,
  },
  chartBarLabel: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.primary,
    marginTop: 8,
  },
  chartBarSubLabel: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: COLORS.mutedText,
    marginTop: 2,
  },
  title: { fontFamily: FONTS.bold, fontSize: 18, color: COLORS.primary },
  subtitle: { fontFamily: FONTS.regular, fontSize: 12, color: COLORS.mutedText, marginBottom: 16 },
  insightItem: { flexDirection: 'row', marginBottom: 16 },
  insightIcon: { fontSize: 24, marginRight: 12 },
  insightTextContainer: { flex: 1 },
  insightTitle: { fontFamily: FONTS.bold, fontSize: 14, color: '#3a2020', marginBottom: 4 },
  insightDesc: { fontFamily: FONTS.regular, fontSize: 13, color: COLORS.mutedText, lineHeight: 18 },

  iconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#f5f6fa',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  insightTitleExtravagant: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: COLORS.primary,
  },
  insightDescExtravagant: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.mutedText,
    lineHeight: 18,
  },

  // Save Money Styles
  smLoadingBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 8,
  },
  smLoadingText: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: COLORS.primary,
  },
  smCardBadge: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.primary,
    backgroundColor: 'rgba(148, 182, 239, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  smStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusBadgeSuccess: {
    backgroundColor: '#E8F5E9',
  },
  statusBadgeWarning: {
    backgroundColor: '#FFF3E0',
  },
  statusBadgeDanger: {
    backgroundColor: '#FFEBEE',
  },
  smStatusBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.primary,
  },
  smMetricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(148, 182, 239, 0.08)',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  smMetricBox: {
    alignItems: 'center',
    flex: 1,
  },
  smMetricLabel: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: 'rgba(153,8,8,0.6)',
    marginBottom: 2,
  },
  smMetricValue: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.primary,
  },
  smProgressWrapper: {
    marginBottom: 10,
  },
  smProgressBarBg: {
    height: 8,
    backgroundColor: 'rgba(148, 182, 239, 0.25)',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 4,
  },
  smProgressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  smProgressLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: 11,
    color: 'rgba(153,8,8,0.7)',
    textAlign: 'right',
  },
  smConfigToggle: {
    paddingVertical: 6,
    alignItems: 'center',
  },
  smConfigToggleText: {
    fontFamily: FONTS.semiBold,
    fontSize: 11,
    color: COLORS.primary,
  },
  smEditorBox: {
    marginTop: 8,
    padding: 10,
    backgroundColor: 'rgba(148, 182, 239, 0.08)',
    borderRadius: 8,
    gap: 8,
  },
  smEditorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  smEditorLabel: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.primary,
  },
  smEditorInput: {
    backgroundColor: '#fff',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(153,8,8,0.2)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    minWidth: 80,
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.primary,
    textAlign: 'right',
  },
  smRecalcButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 6,
    paddingVertical: 6,
    alignItems: 'center',
    marginTop: 4,
  },
  smRecalcButtonText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#fff',
  },
  smHighlightBanner: {
    backgroundColor: 'rgba(25, 118, 210, 0.08)',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  smHighlightLabel: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: 'rgba(153,8,8,0.6)',
    marginBottom: 2,
  },
  smHighlightValue: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.primary,
  },
  smCategoryList: {
    gap: 10,
  },
  smCategoryRow: {
    gap: 4,
  },
  smCategoryHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  smCategoryName: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: COLORS.primary,
  },
  smCategoryAmount: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.primary,
  },
  smCategoryPct: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: 'rgba(153,8,8,0.5)',
  },
  smCatBarBg: {
    height: 6,
    backgroundColor: 'rgba(148, 182, 239, 0.2)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  smCatBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  smRankedList: {
    gap: 8,
  },
  smRankedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(148, 182, 239, 0.06)',
    borderRadius: 8,
  },
  smRankBadge: {
    width: 26,
    height: 20,
    backgroundColor: COLORS.primary,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  smRankBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: '#fff',
  },
  smRankedName: {
    flex: 1,
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: COLORS.primary,
  },
  smRankedPrice: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.primary,
  },

  sectionSubtitle: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: '#636e72',
    marginTop: 2,
    lineHeight: 15,
  },
  subSectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.primary,
  },
  // ── SM-06 SHAP & Anomaly Styles ──
  summaryBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 10,
    gap: 8,
  },
  summaryBannerIcon: {
    fontSize: 16,
  },
  summaryBannerText: {
    flex: 1,
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    lineHeight: 16,
  },
  shapExplanation: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: '#636e72',
    marginBottom: 8,
    lineHeight: 16,
  },
  shapRow: {
    marginBottom: 8,
    backgroundColor: '#F8FAFC',
    padding: 8,
    borderRadius: 8,
  },
  shapTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  shapCategoryName: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: '#2D3748',
  },
  shapPctValue: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#4A5568',
  },
  shapProgressBg: {
    height: 6,
    backgroundColor: '#E2E8F0',
    borderRadius: 3,
    overflow: 'hidden',
  },
  shapProgressFill: {
    height: '100%',
    borderRadius: 3,
  },

  // ── SM-07 Purchase Frequency & Staples Styles ──
  staplesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stapleCard: {
    width: '48%',
    backgroundColor: '#F0F7FF',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#D0E4FF',
  },
  stapleCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  stapleName: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: '#0D47A1',
    marginRight: 4,
  },
  stapleBadge: {
    backgroundColor: '#1976D2',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  stapleBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: '#fff',
  },
  stapleMetricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  stapleRateText: {
    fontFamily: FONTS.semiBold,
    fontSize: 11,
    color: '#1565C0',
  },
  stapleCategoryText: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: '#64748B',
    maxWidth: '45%',
  },
  freqTable: {
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  freqTableHeader: {
    flexDirection: 'row',
    backgroundColor: '#EDF2F7',
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  freqHeadText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#4A5568',
  },
  freqTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderTopWidth: 1,
    borderTopColor: '#EDF2F7',
  },
  freqColName: {
    flex: 2,
  },
  freqColCount: {
    flex: 1,
    textAlign: 'center',
  },
  freqColRate: {
    flex: 1,
    textAlign: 'right',
  },
  freqItemText: {
    fontFamily: FONTS.semiBold,
    fontSize: 12,
    color: '#2D3748',
  },
  freqValueText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: '#4A5568',
  },
  freqRateText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#1976D2',
  },
});

export default styles;

