import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView, KeyboardAvoidingView, Platform, Image } from 'react-native';
import BackgroundLayout from '../components/BackgroundLayout';
import ProgressBar from '../components/ProgressBar';
import PreferenceChip from '../components/PreferenceChip';
import GoalCard from '../components/GoalCard';
import ReviewCard from '../components/ReviewCard';

const green = '#22C55E';
const heroIcons = [
  require('../assets/icons/profile.svg'),
  require('../assets/icons/insights.svg'),
  require('../assets/icons/camera.svg'),
  require('../assets/icons/receipt.svg'),
  require('../assets/icons/settings.svg'),
];
const goals = [
  { icon: '💰', title: 'Save Money', description: 'Track grocery spending and reduce unnecessary expenses.' },
  { icon: '🥗', title: 'Eat Healthy', description: 'Improve nutrition and increase healthy food purchases.' },
  { icon: '💪', title: 'Gain Muscle', description: 'Increase protein intake and muscle-supporting foods.' },
  { icon: '⚖️', title: 'Lose Weight', description: 'Reduce calorie-dense processed foods.' },
  { icon: '❤️', title: 'Manage Diabetes', description: 'Receive lower sugar food recommendations.' },
  { icon: '🫀', title: 'Heart Healthy', description: 'Reduce sodium and unhealthy fats.' },
];
const select = (current, item) => item === 'None' ? (current.includes(item) ? [] : [item]) : current.includes(item) ? current.filter((x) => x !== item) : [...current.filter((x) => x !== 'None'), item];
function Label({ children }) { return <Text style={styles.label}>{children}</Text>; }
function Input({ value, onChangeText, placeholder, keyboardType = 'default' }) { return <TextInput style={styles.input} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#94a99a" keyboardType={keyboardType} />; }
function Chips({ items, value, setValue }) { return <View style={styles.chips}>{items.map((item) => <PreferenceChip key={item} label={item} selected={value.includes(item)} onPress={() => setValue(select(value, item))} />)}</View>; }
export default function OnboardingFlowScreen({ navigation, route }) {
  const [step, setStep] = useState(1);
  const [data, setData] = useState({ fullName: route.params?.name || '', age: '', gender: '', height: '', weight: '', activity: '', food: '', allergies: [], conditions: [], goals: [], budget: '', stores: [], household: '', frequency: '', city: '' });
  const update = (key, value) => setData((d) => ({ ...d, [key]: value }));
  const required = step === 1 ? data.fullName && /^\d+$/.test(data.age) && data.gender && /^\d+(\.\d+)?$/.test(data.height) && /^\d+(\.\d+)?$/.test(data.weight) : step === 2 ? data.activity && data.food : step === 3 ? data.goals.length : step === 4 ? data.budget && data.household && data.frequency : true;
  const go = () => step < 5 ? setStep(step + 1) : navigation.reset({ index: 0, routes: [{ name: 'Main' }] });
  const edit = (target) => setStep(target);
  return <BackgroundLayout><KeyboardAvoidingView style={{ flex: 1, width: '100%' }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><ProgressBar step={step} total={5} /><View style={styles.hero}><View style={styles.icon}><Image source={heroIcons[step - 1]} style={styles.heroIcon} resizeMode="contain" /></View><Text style={styles.title}>{['Tell Us About You', 'Your Lifestyle', 'What are your goals?', 'Shopping Preferences', 'Review & Finish'][step - 1]}</Text><Text style={styles.subtitle}>{['This helps us provide smarter shopping insights.', 'Help us personalize nutrition recommendations.', 'Choose one or more goals.', 'Tell us about your grocery habits.', 'Verify your information before continuing.'][step - 1]}</Text></View>
  {step === 1 && <View><Label>FULL NAME</Label><Input value={data.fullName} onChangeText={(v) => update('fullName', v)} placeholder="Your full name" /><Label>AGE</Label><Input value={data.age} onChangeText={(v) => update('age', v)} placeholder="Your age" keyboardType="numeric" /><Label>GENDER</Label><Chips items={['Male', 'Female', 'Other', 'Prefer not to say']} value={data.gender ? [data.gender] : []} setValue={(v) => update('gender', v[0] || '')} /><Label>HEIGHT (CM)</Label><Input value={data.height} onChangeText={(v) => update('height', v)} placeholder="e.g. 170" keyboardType="decimal-pad" /><Label>WEIGHT (KG)</Label><Input value={data.weight} onChangeText={(v) => update('weight', v)} placeholder="e.g. 65" keyboardType="decimal-pad" /></View>}
  {step === 2 && <View><Label>ACTIVITY LEVEL</Label><Chips items={['Sedentary', 'Lightly Active', 'Moderately Active', 'Very Active', 'Athlete']} value={data.activity ? [data.activity] : []} setValue={(v) => update('activity', v[0] || '')} /><Label>FOOD PREFERENCE</Label><Chips items={['Vegetarian', 'Non-Vegetarian', 'Vegan', 'Eggetarian', 'Pescatarian']} value={data.food ? [data.food] : []} setValue={(v) => update('food', v[0] || '')} /><Label>ALLERGIES (OPTIONAL)</Label><Chips items={['Nuts', 'Dairy', 'Gluten', 'Soy', 'Seafood', 'Eggs', 'None']} value={data.allergies} setValue={(v) => update('allergies', v)} /><Label>MEDICAL CONDITIONS (OPTIONAL)</Label><Chips items={['Diabetes', 'Hypertension', 'High Cholesterol', 'PCOS', 'Thyroid', 'None']} value={data.conditions} setValue={(v) => update('conditions', v)} /></View>}
  {step === 3 && <View>{goals.map((goal) => <GoalCard key={goal.title} goal={goal} selected={data.goals.includes(goal.title)} onPress={() => update('goals', data.goals.includes(goal.title) ? data.goals.filter((g) => g !== goal.title) : [...data.goals, goal.title])} />)}</View>}
  {step === 4 && <View><Label>MONTHLY GROCERY BUDGET (₹)</Label><Input value={data.budget} onChangeText={(v) => update('budget', v)} placeholder="e.g. 8000" keyboardType="numeric" /><Label>PREFERRED STORES (OPTIONAL)</Label><Chips items={['DMart', 'Reliance Fresh', 'Big Bazaar', 'More', "Spencer's", 'Local Market']} value={data.stores} setValue={(v) => update('stores', v)} /><Label>HOUSEHOLD SIZE</Label><Chips items={['1', '2', '3', '4', '5+']} value={data.household ? [data.household] : []} setValue={(v) => update('household', v[0] || '')} /><Label>SHOPPING FREQUENCY</Label><Chips items={['Weekly', 'Bi-weekly', 'Monthly']} value={data.frequency ? [data.frequency] : []} setValue={(v) => update('frequency', v[0] || '')} /><Label>CITY (OPTIONAL)</Label><Input value={data.city} onChangeText={(v) => update('city', v)} placeholder="Your city" /></View>}
  {step === 5 && <View><ReviewCard title="Personal Information" onEdit={() => edit(1)} rows={[["Name", data.fullName], ['Age', data.age], ['Gender', data.gender], ['Height', data.height && `${data.height} cm`], ['Weight', data.weight && `${data.weight} kg`]]} /><ReviewCard title="Lifestyle" onEdit={() => edit(2)} rows={[["Activity", data.activity], ['Food preference', data.food], ['Allergies', data.allergies.join(', ')], ['Conditions', data.conditions.join(', ')]]} /><ReviewCard title="Goals" onEdit={() => edit(3)} rows={[["Selected goals", data.goals.join(', ')]]} /><ReviewCard title="Shopping Preferences" onEdit={() => edit(4)} rows={[["Budget", data.budget && `₹${data.budget}`], ['Stores', data.stores.join(', ')], ['Household', data.household], ['Frequency', data.frequency], ['City', data.city]]} /></View>}
  {!required && <Text style={styles.error}>{step === 3 ? 'Choose at least one goal to continue.' : 'Complete the required fields to continue.'}</Text>}<View style={styles.buttons}>{step > 1 && <TouchableOpacity style={styles.back} onPress={() => setStep(step - 1)}><Text style={styles.backText}>BACK</Text></TouchableOpacity>}<TouchableOpacity disabled={!required} onPress={go} style={[styles.next, !required && styles.disabled]}><Text style={styles.nextText}>{step === 5 ? 'FINISH SETUP' : 'NEXT'}</Text></TouchableOpacity></View></ScrollView></KeyboardAvoidingView></BackgroundLayout>;
}
const styles = StyleSheet.create({ content: { flexGrow: 1, paddingBottom: 26 }, hero: { alignItems: 'center', marginBottom: 21 }, icon: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#dcfce7', alignItems: 'center', justifyContent: 'center', marginBottom: 10 }, heroIcon: { width: 36, height: 36 }, title: { color: '#174d2a', fontFamily: 'serif', fontSize: 23, fontWeight: '700', marginBottom: 6 }, subtitle: { color: '#64756a', fontFamily: 'serif', fontSize: 13, textAlign: 'center', lineHeight: 18 }, label: { color: '#174d2a', fontFamily: 'serif', fontSize: 10, fontWeight: '700', letterSpacing: 1.1, marginBottom: 7, marginTop: 6 }, input: { backgroundColor: '#f6fdf8', borderWidth: 1, borderColor: '#b8d5c1', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontFamily: 'serif', fontSize: 15, color: '#173d28', marginBottom: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 }, buttons: { flexDirection: 'row', gap: 10, marginTop: 12 }, back: { flex: 1, borderWidth: 1, borderColor: green, borderRadius: 28, alignItems: 'center', justifyContent: 'center', paddingVertical: 14 }, backText: { color: green, fontFamily: 'serif', fontWeight: '700', fontSize: 13, letterSpacing: 1 }, next: { flex: 1, backgroundColor: green, borderRadius: 28, alignItems: 'center', paddingVertical: 15, elevation: 3 }, nextText: { color: '#fff', fontFamily: 'serif', fontWeight: '700', fontSize: 13, letterSpacing: 1 }, disabled: { opacity: .42 }, error: { color: '#b45309', fontFamily: 'serif', fontSize: 12, marginTop: 2 } });


